### ISSUE TITLE
RuntimeError: required rank 4 tensor to use channels_last format

### ISSUE THREAD

**Issue by ghost** [Lornatang/Real_ESRGAN-PyTorch#1]
Hi Lorna,
I'm developing a new SRGAN architecture named `ASRGAN` based on your `Real-ESRGAN` implementation.
When I tried to run the `train_realesrnet.py`, this runtime error was thrown.
```
Load all datasets successfully.
Build RealESRNet model successfully.
Define all loss functions successfully.
Define all optimizer functions successfully.
Define all optimizer scheduler successfully.
Check whether the pretrained model is restored...
Traceback (most recent call last):
  File "train_realesrnet.py", line 559, in <module>
    main()
  File "train_realesrnet.py", line 105, in main
    train(model, ema_model, train_prefetcher, pixel_criterion, optimizer, epoch, scaler, writer)
  File "train_realesrnet.py", line 254, in train
    kernel1 = batch_data["kernel1"].to(device=config.device, memory_format=torch.channels_last, non_blocking=True)
RuntimeError: required rank 4 tensor to use channels_last format
```
It seems like `batch_data["kernel1"]` was not a 4D tensor.
My forked repo is not very different from your original repo.
[Here are my personalised commits so far](https://github.com/khoadante/Real-ESRGAN/commits?author=khoadante)
Hope you can take a look at the issue!

Best regards,
Dante

**Comment by Lornatang** [comment]
It seems that I forgot to modify this, I will fix it, thank you for finding this error.
