### ISSUE TITLE
Disable super restoraton

### ISSUE THREAD

**Issue by montis96** [Lornatang/Real_ESRGAN-PyTorch#3]
Is it possible to disable the super restoration process during the inference of the model?

**Comment by Lornatang** [comment]
Statements for annotating model inference

**Comment by montis96** [comment]
I don't think I understood what I need to do...

**Comment by Lornatang** [comment]
Do you want to not call the super-resolution model for processing inference?

**Comment by montis96** [comment]
I want to use the super resolution model without super restoration (the model applies 2 different process, super resolution and super restoriation. But I think is not possible to disable one of them during the inference).

**Comment by Lornatang** [comment]
You can tell me `inference.py` how many lines?
