### ISSUE TITLE
训练速度

### ISSUE THREAD

**Issue by Wakie01** [Lornatang/Real_ESRGAN-PyTorch#6]
不知道有没有方法可以提升一下训练速度，
目前我设置batch_size为16，num_worker为2，image_size依旧为256，然后训练一个batch要2.3秒左右，其中图像退化占了0.5秒多，图像训练用了1.7秒多。

**Comment by Lornatang** [comment]
以下方法你可以参考
数据集全加入内存：快0.3s/image
更换成更高性能显卡：快0.7s/image
多显卡并行训练：快1.1s/image
