### ISSUE TITLE
训练速度

### ISSUE THREAD

**Issue by Wakie01** [Lornatang/Real_ESRGAN-PyTorch#7]
我还是被Real-ESRGAN的训练速度弄得很困扰😩😩
我注意到您复现的BSRGAN与Real-ESRGAN非常非常像，二者的生成器与判别器是完全一样的，不同的只是退化过程，当然训练策略也略微不同（比如Real-ESRGAN在训练过程中使用了USM锐化处理）。
但是，BSRGAN一个批次的训练时间为1.2s左右，而Real-ESRGAN训练一个批次则需约2.6s，即使减去退化所用的约0.8s，生成器与判别器的训练也需要1.8s😖😖😖
总感觉Real-ESRGAN的训练不应该这么慢🥺🥹🥹感觉优化一下代码的话，应该能训练得快一点（狗头）
![Suggestion](https://user-images.githubusercontent.com/33743772/201663133-2f88f259-c581-49bd-9c4e-a771007f499b.gif)

**Comment by Lornatang** [comment]
USM是有加入的，在train()函数里。
Real-ESRGAN训练是很慢，跟RCAN训练时间差不多，而且尺寸也有关系。
还有一种可能是在模型推理中使用较多中间变量，你可以尝试删除。

你多跑几个epoch后再来回复我试一下

**Comment by Lornatang** [comment]
对了，我在对抗网络训练过程中删除了混合精度训练，因为有可能出现Nan
现在找到了解决方法，不想改了~~~~

**Comment by Wakie01** [comment]
现在的Real-ESRGAN代码也是有混合精度训练的吧，毕竟train方法中用到了 `with amp.autocast():` 、`scaler = GradScaler()` 之类的东西。

**Comment by Wakie01** [comment]
我发觉USM锐化非混合精度下只需 0.001s，但在混合精度下则需要0.327s，因此导致了Real-ESRGAN的训练速度下降。
如果除去在混合精度中的USM锐化，则生成器的训练时间为0.859s，判别器为0.280s，再减去退化时间，整体的训练时间也就1.139s，与您之前实现的BSRGAN差不多。

既然如此，在计算像素损失与感知损失时，能不能不对SR进行USM锐化呢？
我注意到xinntao在`realesrgan_model.py`文件（第208行）中关于计算像素损失与感知损失的代码是这样的，似乎没有对SR进行USM锐化，我不知道我想得对不对，毕竟对BasicSR框架不是很看得懂🥹🥹🥹🥹
```python
self.output = self.net_g(self.lq)

l_g_total = 0
loss_dict = OrderedDict()
if (current_iter % self.net_d_iters == 0 and current_iter > self.net_d_init_iters):
    # pixel loss
    if self.cri_pix:
        l_g_pix = self.cri_pix(self.output, l1_gt)
        l_g_total += l_g_pix
        loss_dict['l_g_pix'] = l_g_pix
    # perceptual loss
    if self.cri_perceptual:
        l_g_percep, l_g_style = self.cri_perceptual(self.output, percep_gt)
        if l_g_percep is not None:
            l_g_total += l_g_percep
            loss_dict['l_g_percep'] = l_g_percep
        if l_g_style is not None:
            l_g_total += l_g_style
            loss_dict['l_g_style'] = l_g_style
```

另外，如果退化过程的时间可以再短点就好了，0.8s+的时间太难了😩😩😩

**Comment by Lornatang** [comment]
你是训练带感知的还是L1的？

如果是带感知的，需要加入USM

如果是L1的，则不需要加入USM

**Comment by Wakie01** [comment]
我是训练带感知的😅😅

**Comment by Wakie01** [comment]
容我再尝试辩论一下。
您说得对，训练带感知的确实需要加入USM，但是，不应该是对SR进行USM，而是对HR图像进行USM锐化，一次是在退化前对HR进行USM，还有一次是在HR图像裁剪为256*256后进行USM。

具体可见，xinntao的`realesrgan_model.py`文件中的：
第169行
```python
# random crop
gt_size = self.opt['gt_size']
(self.gt, self.gt_usm), self.lq = paired_random_crop([self.gt, self.gt_usm], self.lq, gt_size,
                                                     self.opt['scale'])

# training pair pool
self._dequeue_and_enqueue()
# sharpen self.gt again, as we have changed the self.gt with self._dequeue_and_enqueue
self.gt_usm = self.usm_sharpener(self.gt)
```
第191行
```python
    def optimize_parameters(self, current_iter):
        # usm sharpening
        l1_gt = self.gt_usm
        percep_gt = self.gt_usm
        gan_gt = self.gt_usm
        if self.opt['l1_gt_usm'] is False:
            l1_gt = self.gt
        if self.opt['percep_gt_usm'] is False:
            percep_gt = self.gt
        if self.opt['gan_gt_usm'] is False:
            gan_gt = self.gt
```

这样的话，在逻辑上也更能说得通吧：使SR图像的纹理更明显。

**Comment by Lornatang** [comment]
最开始是对GT进行USM，然后计算Loss时，对像素损失和内容损失的SR做了USM，当然，这里单独两次USM的问题，导致时间慢

**Comment by Lornatang** [comment]
不好意思，这里写反了

**Comment by Wakie01** [comment]
😁😁😁😁

**Comment by Lornatang** [comment]
代码已经全部修正，现在速度应该可以达到你的理论值

**Comment by Wakie01** [comment]
昨晚跑了一下新版本的代码，特别惊讶，不但时间减了超过一半（生成器的训练时间缩减为0.35s，因此整体训练时间只需1.17s），而且显存的使用也减了几乎一半（从之前的12G变为6点多G），那时真的特别amazing。

今天仔细比较了一下两个版本的代码，虽然看起来似乎变动挺大的，但大体思路还是相似的。
我感觉主要的变动是：
1. 将退化封装为函数。
2. datasets的改动。
3. 将各种loss的权值变为Tensor，并利用GPU加速来计算各种loss。
4. 换了种EMA的实现方式。

我感觉上述4点改动并不能既减时间又减显存，但我真的好好好好好奇为什么能这么神奇🤣🤣🤣🤣   
求指导~~~~

**Comment by Lornatang** [comment]
你看下PyTorch底层啊~~~，当然还有经验~~~

**Comment by Wakie01** [comment]
可以再具体一点吗🥹🥹🥹🥹

**Comment by Lornatang** [comment]
1.减少中间变量，减少显存
2.减少重复USM操作，提速
3.小图操作，提速
4.减少CPU和CUDA通信，提速

**Comment by Wakie01** [comment]
很遗憾🥹🥹🥹，新版本的代码之所以显存和训练时间都减半，是因为realesrgan_config.py文件中`g_num_rrdb=4`😅😅😅

**Comment by Lornatang** [comment]
刚发现，现在修复了，多谢提醒， inference.py也有错误

**Comment by Wakie01** [comment]
大佬，test.py文件中Load the super-resolution model weights部分有点问题😅😅

**Comment by Lornatang** [comment]
谢谢，看到啦，在模型定义那块，最近没时间啊
