### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by xiaokai0215** [Lornatang/Real_ESRGAN-PyTorch#8]
![2](https://user-images.githubusercontent.com/65208666/203779551-0d2cdf49-e4d3-4874-8379-b4c9528ab5d4.png)

**Comment by Lornatang** [comment]
cancel np.ndaaray return

**Comment by xiaokai0215** [comment]
请问具体怎么操作呢

**Comment by xiaokai0215** [comment]
> cancel np.ndaaray return

请问具体怎么操作呢

**Comment by Lornatang** [comment]
把这个->ndarray删除即可
